## Data Cleaning and Preparation

In [1]:
import numpy as np
import pandas as pd

- In Data Analysis, a significant amount of time is spent on data preparation: loading, cleaning, transforming, and rearranging. 
    - Such tasks are often reported to take up 80% or more of an analyst’s time. 
- Pandas provides you with a high-level, flexible, and fast set of tools to enable you to manipulate data into the right form.
- Much of the design and implementation of pandas has been driven by the needs of real-world applications.

## Handling Missing Data
- Missing data occurs commonly in many data analysis applications.
    - all of the descriptive statistics on pandas objects exclude missing data by default.
- The missing data is represented in pandas with the floating-point value NaN (Not a Number). 
    - We call this a sentinel value that can be easily detected.

In [ ]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [ ]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [ ]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

- In pandas, missing data is also referred  as  NA, 
    - it stands for not available. 
- In statistics applications, NA means
    - data that does not exist 
    - data that exists but was not observed

- When cleaning up data for analysis, it is often important to do analysis on the missing data itself to identify data
collection problems or potential biases in the data caused by missing data.
- The built-in Python None value is also treated as NA:

In [ ]:
string_data[0] = None

In [ ]:
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [ ]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### Filtering Out Missing Data

- dropna: Remove missing values.

In [ ]:
from numpy import nan as NA

In [ ]:
import numpy as np

In [ ]:
NA

nan

In [ ]:
np.nan

nan

In [ ]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [ ]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [ ]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [ ]:
data.notnull()

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [ ]:
#dropna is equivalent to
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

- dropna in Dataframe

In [ ]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])

In [ ]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
cleaned = data.dropna()

In [ ]:

cleaned

     0    1    2
0  1.0  6.5  3.0

In [ ]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

- Passing how='all' will only drop rows that are all NA

In [ ]:
data.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
data.dropna(how='any')

     0    1    2
0  1.0  6.5  3.0

In [ ]:
data.dropna(axis=1, how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
data.dropna(axis=0, how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
data.dropna(axis=1, how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

- if you want to keep only rows containing a certain number of observations.

In [ ]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA

In [ ]:
df

          0         1         2
0 -0.251576       NaN       NaN
1 -0.225957       NaN       NaN
2  0.469508       NaN  0.584659
3  1.487620       NaN  2.119301
4  0.725857  0.203071  1.530177
5 -0.278299  1.636577 -0.717995
6 -0.006226  0.030861 -2.345888

In [ ]:
df.dropna()

          0         1         2
4  0.725857  0.203071  1.530177
5 -0.278299  1.636577 -0.717995
6 -0.006226  0.030861 -2.345888

In [ ]:
df.dropna(thresh=2)

          0         1         2
2  0.469508       NaN  0.584659
3  1.487620       NaN  2.119301
4  0.725857  0.203071  1.530177
5 -0.278299  1.636577 -0.717995
6 -0.006226  0.030861 -2.345888

### Filling In Missing Data

- *fillna*: Fill NA/NaN values using the specified method

In [ ]:
df

          0         1         2
0  0.079951       NaN       NaN
1  0.598211       NaN       NaN
2 -1.357878       NaN  0.483164
3 -0.993119       NaN  0.377519
4 -1.651456  0.815283  1.163639
5  0.227592 -0.668231  0.620279
6  1.924692  0.065528 -1.284205

In [ ]:
df.fillna(42)

          0          1          2
0  0.079951  42.000000  42.000000
1  0.598211  42.000000  42.000000
2 -1.357878  42.000000   0.483164
3 -0.993119  42.000000   0.377519
4 -1.651456   0.815283   1.163639
5  0.227592  -0.668231   0.620279
6  1.924692   0.065528  -1.284205

In [ ]:
df

          0         1         2
0 -0.251576       NaN       NaN
1 -0.225957       NaN       NaN
2  0.469508       NaN  0.584659
3  1.487620       NaN  2.119301
4  0.725857  0.203071  1.530177
5 -0.278299  1.636577 -0.717995
6 -0.006226  0.030861 -2.345888

In [ ]:
#if the value to fill in depends on the column
df.fillna({1: 0.5, 2: 0})

          0         1         2
0 -0.251576  0.500000  0.000000
1 -0.225957  0.500000  0.000000
2  0.469508  0.500000  0.584659
3  1.487620  0.500000  2.119301
4  0.725857  0.203071  1.530177
5 -0.278299  1.636577 -0.717995
6 -0.006226  0.030861 -2.345888

In [ ]:
df

          0         1         2
0 -0.251576       NaN       NaN
1 -0.225957       NaN       NaN
2  0.469508       NaN  0.584659
3  1.487620       NaN  2.119301
4  0.725857  0.203071  1.530177
5 -0.278299  1.636577 -0.717995
6 -0.006226  0.030861 -2.345888

In [ ]:
df.fillna(0, inplace=True)

In [ ]:
df

          0         1         2
0 -0.251576  0.000000  0.000000
1 -0.225957  0.000000  0.000000
2  0.469508  0.000000  0.584659
3  1.487620  0.000000  2.119301
4  0.725857  0.203071  1.530177
5 -0.278299  1.636577 -0.717995
6 -0.006226  0.030861 -2.345888

- computing a value

In [ ]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

          0         1         2
0  0.471215  0.581603 -0.731619
1 -1.457867  0.194161  0.148402
2 -1.942438       NaN -2.335805
3 -1.065249       NaN  0.103944
4  0.649876       NaN       NaN
5 -0.390888       NaN       NaN

In [ ]:
df.fillna(method='ffill')

          0         1         2
0  0.471215  0.581603 -0.731619
1 -1.457867  0.194161  0.148402
2 -1.942438  0.194161 -2.335805
3 -1.065249  0.194161  0.103944
4  0.649876  0.194161  0.103944
5 -0.390888  0.194161  0.103944

In [ ]:
#limit For forward and backward filling, maximum number of consecutive periods to fill
df.fillna(method='ffill', limit=2)

          0         1         2
0  0.471215  0.581603 -0.731619
1 -1.457867  0.194161  0.148402
2 -1.942438  0.194161 -2.335805
3 -1.065249  0.194161  0.103944
4  0.649876       NaN  0.103944
5 -0.390888       NaN  0.103944

In [ ]:
# using mean
df.mean()

0   -0.622559
1    0.387882
2   -0.703769
dtype: float64

In [ ]:
#we can use other functions
df.fillna(df.mean())

          0         1         2
0  0.471215  0.581603 -0.731619
1 -1.457867  0.194161  0.148402
2 -1.942438  0.387882 -2.335805
3 -1.065249  0.387882  0.103944
4  0.649876  0.387882 -0.703769
5 -0.390888  0.387882 -0.703769

## Data Transformation

### Removing Duplicates

- *duplicated*
- drop_duplicated

In [ ]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [ ]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [ ]:
# data['k1'].duplicated()
data.duplicated(['k1'])

0    False
1    False
2     True
3     True
4     True
5     True
6     True
dtype: bool

In [ ]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [ ]:
data['v1'] = range(7)
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [ ]:
data.drop_duplicates(['k1'])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [ ]:
data.drop_duplicates(['k1', 'k2'], keep='last')

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

- map: Map values of Series according to input correspondence.

In [ ]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                             'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

1. passing dictionary

In [ ]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

meat_to_animal

{'bacon': 'pig',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon',
 'pastrami': 'cow',
 'pulled pork': 'pig'}

In [ ]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [ ]:
data['animal'] = lowercased.map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

### Replacing Values

- *replace*: Replace values given in *to_replace* with value.

In [ ]:
data = pd.Series([1., -999., 2., -998., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -998.0
4   -1000.0
5       3.0
dtype: float64

In [ ]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3    -998.0
4   -1000.0
5       3.0
dtype: float64

In [ ]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [ ]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [ ]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Discretization and Binning

- *cut*: Bin values into discrete intervals. Use cut when you need to segment and sort data values into bins

In [ ]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [ ]:
bins = [18, 25, 35, 60, 100]

In [ ]:
cats = pd.cut(ages, bins)

In [ ]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [ ]:
type(cats)

pandas.core.arrays.categorical.Categorical

In [ ]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [ ]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [ ]:
#These are the bin counts for the result of pandas.cut.
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [ ]:
#parenthesis means that the side is open, 
#while the square bracket means it is closed (inclusive). 
#You can change which side is closed by passing right=False:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [ ]:
#You can also pass your own bin names by passing a list or array to the labels option:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [ ]:
# passing an integer, it will compute
#equal-length bins based on the minimum and maximum values in the data.

data = np.random.rand(20)
data

array([0.05685672, 0.47548688, 0.35684812, 0.65375121, 0.72203043,
       0.13207171, 0.9226366 , 0.15372456, 0.95561138, 0.59627707,
       0.88463277, 0.20978523, 0.03061795, 0.67963826, 0.51784867,
       0.43777796, 0.8599099 , 0.28592993, 0.84760982, 0.3486577 ])

In [ ]:
pd.cut(data, 2, precision=3)

[(0.0297, 0.493], (0.0297, 0.493], (0.0297, 0.493], (0.493, 0.956], (0.493, 0.956], ..., (0.0297, 0.493], (0.493, 0.956], (0.0297, 0.493], (0.493, 0.956], (0.0297, 0.493]]
Length: 20
Categories (2, interval[float64]): [(0.0297, 0.493] < (0.493, 0.956]]

In [ ]:
pd.cut(ages, 2)

[(19.959, 40.5], (19.959, 40.5], (19.959, 40.5], (19.959, 40.5], (19.959, 40.5], ..., (19.959, 40.5], (40.5, 61.0], (40.5, 61.0], (40.5, 61.0], (19.959, 40.5]]
Length: 12
Categories (2, interval[float64]): [(19.959, 40.5] < (40.5, 61.0]]

### Permutation and Random Sampling

- *np.random.permutation* -> *pd.DataFrame.take*
- *pd.DataFrame.sample*

In [ ]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [ ]:
df

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [ ]:
sampler = np.random.permutation(5)

In [ ]:
sampler

array([3, 4, 1, 0, 2])

In [ ]:
df

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [ ]:
df.take(sampler[-2:])

   0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [ ]:
# you can use the sample method with a random subset without replacement
df.sample(n=3)

    0   1   2   3
1   4   5   6   7
0   0   1   2   3
4  16  17  18  19

In [ ]:
#a sample with replacement (to allow repeat choices) is generated by passing replace=True to sample
df.sample(n=5, replace=True)

    0   1   2   3
4  16  17  18  19
0   0   1   2   3
3  12  13  14  15
2   8   9  10  11
3  12  13  14  15

### Computing Indicator/Dummy Variables/ One Hot Encoding (OHE)
- This converts a categorical variable into a “dummy” or “indicator” matrix. 

- If a column in a DataFrame has k distinct values, 
    - you would derive a matrix or DataFrame with k columns containing all 1s and 0s. 
- pandas has a get_dummies function for doing this

In [ ]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

In [ ]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
pd.get_dummies(df['key'])

   a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [ ]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [ ]:
dummies

   key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [ ]:
#to join the result in the original dataframe
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

   data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

# Data Wrangling: Clean, Transform, Merge, Reshape

In [ ]:
import pandas as pd
import numpy as np

- Much of the programming work in data analysis and modeling is spent on data preparation
    - loading, cleaning, transforming, and rearranging. 
    -  the way that data is stored in files or databases is not the way you need it .
- Fortunately, pandas along with the Python standard library provide you with a high-level, flexible, and high-performance set of core manipulations and algorithms to enable you to wrangle data into the right form without much trouble.

## Hierarchical Indexing

- Hierarchical indexing  enables you to have multiple (two or more) index levels on an axis.

In [ ]:
data = pd.Series(np.random.randn(9),
                 index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                        [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1   -1.955721
   2   -1.312649
   3    0.296382
b  1   -0.986512
   3    0.302984
c  1   -0.626144
   2   -0.033257
d  2   -0.749779
   3    1.250929
dtype: float64

In [ ]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [ ]:
#codes expresses how the indexes are combined
codesArr = np.array([[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 2, 0, 1, 1, 2]])

In [ ]:
codesArr

array([[0, 0, 0, 1, 1, 2, 2, 3, 3],
       [0, 1, 2, 0, 2, 0, 1, 1, 2]])

- partial indexing

In [ ]:
data["a"]

1   -2.069560
2   -2.169479
3   -0.598015
dtype: float64

In [ ]:
data["b"]

1   -0.822776
3    0.780830
dtype: float64

In [ ]:
data["b":"d"]

b  1   -0.822776
   3    0.780830
c  1    1.075183
   2   -1.133136
d  2    0.297199
   3   -0.867633
dtype: float64

In [ ]:
data[["b","d"]]

b  1   -0.822776
   3    0.780830
d  2    0.297199
   3   -0.867633
dtype: float64

In [ ]:
data[:,3]

a   -0.598015
b    0.780830
d   -0.867633
dtype: float64

In [ ]:
data

a  1   -2.069560
   2   -2.169479
   3   -0.598015
b  1   -0.822776
   3    0.780830
c  1    1.075183
   2   -1.133136
d  2    0.297199
   3   -0.867633
dtype: float64

In [ ]:
data.unstack()

          1         2         3
a -2.069560 -2.169479 -0.598015
b -0.822776       NaN  0.780830
c  1.075183 -1.133136       NaN
d       NaN  0.297199 -0.867633

In [ ]:
data.unstack().stack()

a  1   -2.069560
   2   -2.169479
   3   -0.598015
b  1   -0.822776
   3    0.780830
c  1    1.075183
   2   -1.133136
d  2    0.297199
   3   -0.867633
dtype: float64

- In DataFrame, either axis can have a hierarchical index

In [ ]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                     columns=[['Ohio', 'Ohio', 'Colorado'],
                              ['Green', 'Red', 'Green']])
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [ ]:
frame["Ohio"]

     Green  Red
a 1      0    1
  2      3    4
b 1      6    7
  2      9   10

In [ ]:
frame.loc["a",:]

   Ohio     Colorado
  Green Red    Green
1     0   1        2
2     3   4        5

In [ ]:
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

- statistics by level

In [ ]:
frame.sum(level='key2')

state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16

In [ ]:
frame.sum(level='color', axis=1)

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

## Database-style DataFrame Merges

- pandas.merge connects rows in DataFrames based on one or more keys. 
- pandas.concat glues or stacks together objects along an axis.
- combine_first instance method enables splicing together overlapping data to fill in missing values in one object with values from another.

- Merge or join operations combine datasets by linking rows using one or more keys.
    - These operations are central to relational databases (e.g., SQL-based).

In [ ]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                    'data2': range(3)})

In [ ]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [ ]:
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [ ]:
pd.merge(df1, df2) # natural join

  key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [ ]:
pd.merge(df1, df2, on='key') # join using the attribute specified in the "on" parameter

  key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [ ]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
                    'data2': range(3)})

In [ ]:
df3

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [ ]:
df4

  rkey  data2
0    a      0
1    b      1
2    d      2

In [ ]:
#we can specify the join attributes on the left and right tables
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [ ]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey', how='left')

  lkey  data1 rkey  data2
0    b      0    b    1.0
1    b      1    b    1.0
2    a      2    a    0.0
3    c      3  NaN    NaN
4    a      4    a    0.0
5    a      5    a    0.0
6    b      6    b    1.0

In [ ]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey', how='right')

  lkey  data1 rkey  data2
0    a    2.0    a      0
1    a    4.0    a      0
2    a    5.0    a      0
3    b    0.0    b      1
4    b    1.0    b      1
5    b    6.0    b      1
6  NaN    NaN    d      2

In [ ]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey', how='outer')

  lkey  data1 rkey  data2
0    b    0.0    b    1.0
1    b    1.0    b    1.0
2    b    6.0    b    1.0
3    a    2.0    a    0.0
4    a    4.0    a    0.0
5    a    5.0    a    0.0
6    c    3.0  NaN    NaN
7  NaN    NaN    d    2.0

In [ ]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
                     'key2': ['one', 'two', 'one'],
                     'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                      'key2': ['one', 'one', 'one', 'two'],
                      'rval': [4, 5, 6, 7]})

In [ ]:
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [ ]:
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [ ]:
pd.merge(left, right, on=['key1', 'key2'], how='outer')

  key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

- treatment of overlapping column names.
-  merge has a suffixes option for specifying strings to appendto overlapping names in the left and right DataFrame objects

In [ ]:
pd.merge(left, right, on='key1')

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [ ]:
pd.merge(left, right, on='key1', suffixes=('_left', '_right'))

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

- Merging on Index
    - the merge key(s) in a DataFrame can be found in its index.

In [ ]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                      'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

In [ ]:
left1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [ ]:
right1

   group_val
a        3.5
b        7.0

In [ ]:
pd.merge(left1, right1, left_on='key', right_index=True)

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [ ]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [ ]:
#we can use the indexes on both tables

left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                     index=['a', 'c', 'e'],
                     columns=['Ohio', 'Nevada'])
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                      index=['b', 'c', 'd', 'e'],
                      columns=['Missouri', 'Alabama'])

In [ ]:
left2

   Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [ ]:
right2

   Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [ ]:
pd.merge(left2, right2,  left_index=True, right_index=True)

   Ohio  Nevada  Missouri  Alabama
c   3.0     4.0       9.0     10.0
e   5.0     6.0      13.0     14.0

- DataFrame has a convenient **join** instance for merging by index
- it performs a left join on the join keys, exactly preserving the left frame’s row index

In [ ]:
left2.join(right2)

   Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
c   3.0     4.0       9.0     10.0
e   5.0     6.0      13.0     14.0

In [ ]:
right2.join(left2)

   Missouri  Alabama  Ohio  Nevada
b       7.0      8.0   NaN     NaN
c       9.0     10.0   3.0     4.0
d      11.0     12.0   NaN     NaN
e      13.0     14.0   5.0     6.0

In [ ]:
left2.join(right2, how ='inner')

   Ohio  Nevada  Missouri  Alabama
c   3.0     4.0       9.0     10.0
e   5.0     6.0      13.0     14.0

In [ ]:
# we can join by index and attribute as with the merge

left1.join(right1, on='key')

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [ ]:
#joining more tables
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                       index=['a', 'c', 'e', 'f'],
                       columns=['New York', 'Oregon'])
another

   New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [ ]:
left2.join([right2, another])

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

## Concatenating Along an Axis

- Another kind of data combination operation is referred to interchangeably as concatenation, binding, or stacking

In [ ]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [ ]:
np.concatenate([arr, arr])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In the context of pandas objects such as Series and DataFrame, having labeled axes
enable you to further generalize array concatenation

In [2]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])

In [ ]:
s1

a    0
b    1
dtype: int64

In [ ]:
s2

c    2
d    3
e    4
dtype: int64

In [ ]:
s3

f    5
g    6
dtype: int64

In [14]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [11]:
pd.concat([s1,s2,s3], axis =1)

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [18]:
s4 = pd.concat([s1, s3])

In [ ]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [ ]:
pd.concat([s1, s4], axis=1)

     0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [19]:
pd.concat([s1, s4], axis=1, join ='inner')

   0  1
a  0  0
b  1  1

- A potential issue is that the concatenated pieces are not identifiable in the result.

In [ ]:
pd.concat([s1,s2,s3], keys=['s1','s2','s3'])

s1  a    0
    b    1
s2  c    2
    d    3
    e    4
s3  f    5
    g    6
dtype: int64

In [ ]:
pd.concat([s1,s2,s3], keys=['s1','s2','s3']).unstack()

      a    b    c    d    e    f    g
s1  0.0  1.0  NaN  NaN  NaN  NaN  NaN
s2  NaN  NaN  2.0  3.0  4.0  NaN  NaN
s3  NaN  NaN  NaN  NaN  NaN  5.0  6.0

- The same logic extends to DataFrame objects:

In [ ]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
                   columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
                   columns=['three', 'four'])

In [ ]:
df1

   one  two
a    0    1
b    2    3
c    4    5

In [ ]:
df2

   three  four
a      5     6
c      7     8

In [ ]:
pd.concat([df1,df2])

   one  two  three  four
a  0.0  1.0    NaN   NaN
b  2.0  3.0    NaN   NaN
c  4.0  5.0    NaN   NaN
a  NaN  NaN    5.0   6.0
c  NaN  NaN    7.0   8.0

In [ ]:
pd.concat([df1,df2], axis =1)

   one  two  three  four
a    0    1    5.0   6.0
b    2    3    NaN   NaN
c    4    5    7.0   8.0

In [ ]:
pd.concat([df1,df2], axis =1, keys =['df1','df2'])

  df1       df2
  one two three four
a   0   1   5.0  6.0
b   2   3   NaN  NaN
c   4   5   7.0  8.0

- when the row index does not contain any relevant data

In [ ]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])

In [ ]:
df1

          a         b         c         d
0 -0.915916 -0.286016 -0.293797 -0.300203
1  1.370099 -1.327259  0.150033  1.456341
2  1.318642  0.312499  1.685567  0.254629

In [ ]:
df2

          b         d         a
0 -0.629313  0.660454  0.745494
1  1.162302  1.337298  0.986611

In [ ]:
pd.concat([df1,df2])

          a         b         c         d
0 -0.915916 -0.286016 -0.293797 -0.300203
1  1.370099 -1.327259  0.150033  1.456341
2  1.318642  0.312499  1.685567  0.254629
0  0.745494 -0.629313       NaN  0.660454
1  0.986611  1.162302       NaN  1.337298

In [ ]:
pd.concat([df1,df2], ignore_index=True)

          a         b         c         d
0 -0.915916 -0.286016 -0.293797 -0.300203
1  1.370099 -1.327259  0.150033  1.456341
2  1.318642  0.312499  1.685567  0.254629
3  0.745494 -0.629313       NaN  0.660454
4  0.986611  1.162302       NaN  1.337298

## [Bonus] Combining Data with Overlap

- You may have two datasets whose indexes overlap in full or part

In [ ]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
              index=['f', 'e', 'd', 'c', 'b', 'a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),
              index=['f', 'e', 'd', 'c', 'b', 'a'])

In [ ]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [ ]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [ ]:
b[-1]=np.nan

In [ ]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [ ]:
np.where(pd.isnull(a), b, a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

- the **combine_first method** performs the equivalent of this operation along with pandas’s usual data alignment logic

In [ ]:
b[:].combine_first(a)

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [ ]:
b[::-1].combine_first(a)

a    NaN
b    4.0
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [ ]:
a[::-1].combine_first(b)

a    NaN
b    4.5
c    3.5
d    2.0
e    2.5
f    0.0
dtype: float64

- With DataFrames, combine_first does the same thing column by column
    - you can think of it as “patching” missing data in the calling object with data from the object you pass

In [ ]:
df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],
                    'b': [np.nan, 2., np.nan, 6.],
                    'c': range(2, 18, 4)})
df2 = pd.DataFrame({'a': [5., 4., np.nan, 3., 7.],
                    'b': [np.nan, 3., 4., 6., 8.]})

In [ ]:
df1

     a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [ ]:
df2

     a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [ ]:
df1.combine_first(df2)

     a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [ ]:
df2.combine_first(df1)

     a    b     c
0  5.0  NaN   2.0
1  4.0  3.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

## [BONUS] Reshaping and Pivoting
- There are a number of basic operations for rearranging tabular data. 
- These are referred to as reshape or pivot operations.

- Hierarchical indexing provides a consistent way to rearrange data in a DataFrame.

- stack
    - This “rotates” or pivots from the columns in the data to the rows
- unstack
    - This pivots from the rows into the columns

In [ ]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(['Ohio', 'Colorado'], name='state'),
                    columns=pd.Index(['one', 'two', 'three']))

In [ ]:
data

          one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [ ]:
data.stack()

state
Ohio      one      0
          two      1
          three    2
Colorado  one      3
          two      4
          three    5
dtype: int64

In [ ]:
stacked = data.stack()

In [ ]:
stacked

state
Ohio      one      0
          two      1
          three    2
Colorado  one      3
          two      4
          three    5
dtype: int64

In [ ]:
stacked.unstack()

          one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [ ]:
#By default the innermost level is unstacked (same with stack). 
#You can unstack a different level by passing a level number or name:
stacked.unstack(0)

state  Ohio  Colorado
one       0         3
two       1         4
three     2         5

- Unstacking might introduce missing data

In [ ]:
s1 = pd.Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 5, 6], index=['c', 'd', 'e'])

In [ ]:
s1

a    0
b    1
c    2
d    3
dtype: int64

In [ ]:
s2

c    4
d    5
e    6
dtype: int64

In [ ]:
data2 = pd.concat([s1, s2], keys=['one', 'two'])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [ ]:
data2.unstack()

       a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

# Data Aggregation and Group Operations

- Categorizing a dataset and applying a function to each group is often a critical component of a data analysis workflow. 
- After loading, merging, and preparing a dataset, you may need to compute group statistics or pivot tables for reporting or visualization purposes.

### GroupBy Mechanics
- data contained in a pandas object is split into groups based on one or more keys.
    - The splitting is performed on a particular axis of an object. 
        - For example, a DataFrame can be grouped on its rows (axis=0) or its columns (axis=1).
- a function is applied to each group, producing a new value.
- the results of all those function applications are combined into a result object. 

<img src="https://drive.google.com/uc?id=1B559BfpzVoV6i9QdzmeA-GLrGdZTd-2s" width=500>

In [ ]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),
                   'data2' : np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one  0.019194  0.207089
1    a  two -0.452715 -0.381667
2    b  one  0.906950 -1.120732
3    b  two -0.401363 -0.780774
4    a  one  0.205485 -1.054052

- We want to compute the mean of the data1 column using the labels from key1.

In [ ]:
grouped = df['data1'].groupby(df['key1'])

- This grouped variable is now a GroupBy object. 
- It has not actually computed anything yet except for some intermediate data about the group key df['key1']. 
- The idea is that this object has all of the information needed to then apply some operation to each of the groups.

In [ ]:
grouped

In [ ]:
grouped.mean()

key1
a   -0.076012
b    0.252793
Name: data1, dtype: float64

In [ ]:
grouped.sum()

key1
a   -0.228036
b    0.505587
Name: data1, dtype: float64

In [ ]:
grouped.max()

key1
a    0.205485
b    0.906950
Name: data1, dtype: float64

In [ ]:
df['data1'].groupby([df['key1'], df['key2']]).mean()

key1  key2
a     one     0.112339
      two    -0.452715
b     one     0.906950
      two    -0.401363
Name: data1, dtype: float64

In [ ]:
df['data1'].groupby([df['key1'], df['key2']]).mean().unstack()

key2       one       two
key1
a     0.112339 -0.452715
b     0.906950 -0.401363

In [ ]:
df['data1'].groupby(df['key1']).mean()

key1
a   -0.076012
b    0.252793
Name: data1, dtype: float64

In [ ]:
df.groupby(df['key1']).mean()

         data1     data2
key1
a    -0.076012 -0.409543
b     0.252793 -0.950753

- Note that there is no key2 column in the result. 
    - df['key2'] is not numeric data. 
    - By default, all of the numeric columns are aggregated

    
    
- the method size returns a Series containing group sizes

In [ ]:
df.groupby(['key1', 'key2']).size()

key1  key2
a     one     2
      two     1
b     one     1
      two     1
dtype: int64

- Iterating Over Groups
    - The GroupBy object supports iteration, 
    - It generates a sequence of 2-tuples containing the group name along with the chunk of data

In [ ]:
for name, group in df.groupby('key1'):
    print(name)
    print(group)
    print("\n\n")

a
  key1 key2     data1     data2
0    a  one  0.019194  0.207089
1    a  two -0.452715 -0.381667
4    a  one  0.205485 -1.054052



b
  key1 key2     data1     data2
2    b  one  0.906950 -1.120732
3    b  two -0.401363 -0.780774

In [ ]:
# multiple keys in the group by clause
for (k1, k2), group in df.groupby(['key1', 'key2']):
    print((k1, k2))
    print(group)
    print("\n\n")

('a', 'one')
  key1 key2     data1     data2
0    a  one  0.019194  0.207089
4    a  one  0.205485 -1.054052



('a', 'two')
  key1 key2     data1     data2
1    a  two -0.452715 -0.381667



('b', 'one')
  key1 key2    data1     data2
2    b  one  0.90695 -1.120732



('b', 'two')
  key1 key2     data1     data2
3    b  two -0.401363 -0.780774

- you can choose to do whatever you want with the pieces of data. 
- A recipe you may find useful is computing a dict of the data pieces as a one-liner:

In [ ]:
pieces = dict(list(df.groupby('key1')))

In [ ]:
pieces

{'a':   key1 key2     data1     data2
 0    a  one -0.164725  1.638132
 1    a  two  0.207589 -1.514719
 4    a  one -1.117607 -0.688100, 'b':   key1 key2     data1     data2
 2    b  one  0.944196  0.612832
 3    b  two -0.420889 -0.614408}

In [ ]:
pieces['a']

  key1 key2     data1     data2
0    a  one -2.005401  0.144292
1    a  two  0.320642 -0.598033
4    a  one  0.197859 -1.284013

In [ ]:
pieces['b']

  key1 key2     data1     data2
2    b  one  0.229067  0.221228
3    b  two -0.165283  1.264144

- By default groupby groups on axis=0, but you can group on any of the other axes.

In [ ]:
df.dtypes

key1      object
key2      object
data1    float64
data2    float64
dtype: object

In [ ]:
grouped = df.groupby(df.dtypes, axis=1)

In [ ]:
for dtype, group in grouped:
    print(dtype)
    print(group)

float64
      data1     data2
0 -2.005401  0.144292
1  0.320642 -0.598033
2  0.229067  0.221228
3 -0.165283  1.264144
4  0.197859 -1.284013
object
  key1 key2
0    a  one
1    a  two
2    b  one
3    b  two
4    a  one

### Selecting a Column or Subset of Columns
- Indexing a GroupBy object created from a DataFrame with a column name or array of column names has the effect of column subsetting for aggregation

In [ ]:
df.groupby('key1')['data1'] 
# it is equal to df['data1'].groupby(df['key1'])

In [ ]:
df.groupby('key1')[['data2']]
# it is equal to df[['data2']].groupby(df['key1'])

In [ ]:
df.groupby('key1')['data2'].mean()

key1
a   -0.579251
b    0.742686
Name: data2, dtype: float64

### Grouping with Dicts and Series

In [ ]:
people = pd.DataFrame(np.random.randn(5, 5),
                      columns=['a', 'b', 'c', 'd', 'e'],
                      index=['Joe', 'Steve', 'Wes', 'Jim', 'Travis'])

In [ ]:
people

               a         b         c         d         e
Joe    -0.351749 -0.542448 -0.382813 -0.449896 -0.680404
Steve   2.090339  0.255644  0.001924  0.139754  1.209961
Wes     0.763162  0.844741  0.789671  1.621206  0.514205
Jim    -0.109227  0.650612 -0.794183 -1.439502 -0.637658
Travis -0.562872 -0.520418  0.244025  0.120481 -0.592518

In [ ]:
mapping = {'a': 'red', 'b': 'red', 'c': 'blue',
           'd': 'blue', 'e': 'orange'}

In [ ]:
by_column = people.groupby(mapping, axis=1)

In [ ]:
by_column.sum()

            blue    orange       red
Joe    -0.832710 -0.680404 -0.894197
Steve   0.141678  1.209961  2.345984
Wes     2.410877  0.514205  1.607904
Jim    -2.233685 -0.637658  0.541386
Travis  0.364506 -0.592518 -1.083290

- The same functionality holds for Series, which can be viewed as a fixed-size mapping

In [ ]:
map_series = pd.Series(mapping)

In [ ]:
map_series

a       red
b       red
c      blue
d      blue
e    orange
dtype: object

In [ ]:
by_columnSeries = people.groupby(mapping, axis=1)

In [ ]:
by_columnSeries.mean()

            blue    orange       red
Joe    -0.416355 -0.680404 -0.447098
Steve   0.070839  1.209961  1.172992
Wes     1.205438  0.514205  0.803952
Jim    -1.116842 -0.637658  0.270693
Travis  0.182253 -0.592518 -0.541645

### Grouping with Functions
- Any function passed as a group key will be called once per index value, with the return values being used as the group names.

In [ ]:
people

               a         b         c         d         e
Joe    -0.351749 -0.542448 -0.382813 -0.449896 -0.680404
Steve   2.090339  0.255644  0.001924  0.139754  1.209961
Wes     0.763162  0.844741  0.789671  1.621206  0.514205
Jim    -0.109227  0.650612 -0.794183 -1.439502 -0.637658
Travis -0.562872 -0.520418  0.244025  0.120481 -0.592518

In [ ]:
people.groupby(len).sum()

          a         b         c         d         e
3  0.302186  0.952906 -0.387326 -0.268192 -0.803856
5  2.090339  0.255644  0.001924  0.139754  1.209961
6 -0.562872 -0.520418  0.244025  0.120481 -0.592518

- Mixing functions with arrays, dicts, or Series is not a problem

In [ ]:
key_list = ['one', 'one', 'one', 'two', 'two']
people.groupby([len, key_list]).min()

              a         b         c         d         e
3 one -0.351749 -0.542448 -0.382813 -0.449896 -0.680404
  two -0.109227  0.650612 -0.794183 -1.439502 -0.637658
5 one  2.090339  0.255644  0.001924  0.139754  1.209961
6 two -0.562872 -0.520418  0.244025  0.120481 -0.592518

### Data Aggregation

<img src="https://drive.google.com/uc?id=1Azj6fJq9KLaSZoA0GSLl2OwJCUzw-Ba2" width=500>

- Aggregations refer to any data transformation that produces scalar values from arrays. 

- Many common aggregations, such as those found in the above table, have optimized implementations. 

- You are not limited to only this set of methods.
    - For example quantile is not explicitly implemented for GroupBy, it is a Series method and thus available for use.

In [ ]:
grouped = df.groupby('key1')
grouped['data1'].quantile()

key1
a    0.197859
b    0.031892
Name: data1, dtype: float64

-  you can implement a custom function
- you have to pass the function to the agg() method

In [ ]:
def peak_to_peak(arr):
    return arr.max() - arr.min()

In [ ]:
grouped = df.groupby('key1')

In [ ]:
grouped['data1'].agg(peak_to_peak)

key1
a    2.326043
b    0.394351
Name: data1, dtype: float64

In [ ]:
#Note that the method describes works applied to groups
grouped.describe()

     data1                      ...     data2
     count      mean       std  ...       50%       75%       max
key1                            ...
a      3.0 -0.495633  1.308938  ... -0.598033 -0.226871  0.144292
b      2.0  0.031892  0.278848  ...  0.742686  1.003415  1.264144

[2 rows x 16 columns]

## [BONUS] Column-Wise and Multiple Function Application

In [ ]:
#caricare il file su colab
tips = pd.read_csv('tips.csv')

In [ ]:
tips.head(10)

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4
5       25.29  4.71     No  Sun  Dinner     4
6        8.77  2.00     No  Sun  Dinner     2
7       26.88  3.12     No  Sun  Dinner     4
8       15.04  1.96     No  Sun  Dinner     2
9       14.78  3.23     No  Sun  Dinner     2

In [ ]:
tips.shape

(244, 6)

In [ ]:
tips['tip_pct'] = tips['tip'] / tips['total_bill']

In [ ]:
tips.head(10)

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808
5       25.29  4.71     No  Sun  Dinner     4  0.186240
6        8.77  2.00     No  Sun  Dinner     2  0.228050
7       26.88  3.12     No  Sun  Dinner     4  0.116071
8       15.04  1.96     No  Sun  Dinner     2  0.130319
9       14.78  3.23     No  Sun  Dinner     2  0.218539

- aggregating a Series or all of the columns of a DataFrame is a matter of using aggregate with the desired function or calling a method like mean or std. 
- you may want to aggregate using a different function depending on the column, or multiple functions at once.

In [ ]:
#this is a simple grouping
grouped = tips.groupby(['day', 'smoker'])

In [ ]:
grouped_pct = grouped['tip_pct']

In [ ]:
# for simple statistics, you can pass the name of the function as a string

grouped_pct.agg('mean')

day   smoker
Fri   No        0.151650
      Yes       0.174783
Sat   No        0.158048
      Yes       0.147906
Sun   No        0.160113
      Yes       0.187250
Thur  No        0.160298
      Yes       0.163863
Name: tip_pct, dtype: float64

In [ ]:
# If you pass a list of functions or function names , you get back a DataFrame with column names taken from the functions
grouped_pct.agg(['mean', 'std', peak_to_peak])

                 mean       std  peak_to_peak
day  smoker
Fri  No      0.151650  0.028123      0.067349
     Yes     0.174783  0.051293      0.159925
Sat  No      0.158048  0.039767      0.235193
     Yes     0.147906  0.061375      0.290095
Sun  No      0.160113  0.042347      0.193226
     Yes     0.187250  0.154134      0.644685
Thur No      0.160298  0.038774      0.193350
     Yes     0.163863  0.039389      0.151240

In [ ]:
#
grouped_pct.agg([('Media', 'mean'), ('Deviazione std', np.std)])

                Media  Deviazione std
day  smoker
Fri  No      0.151650        0.028123
     Yes     0.174783        0.051293
Sat  No      0.158048        0.039767
     Yes     0.147906        0.061375
Sun  No      0.160113        0.042347
     Yes     0.187250        0.154134
Thur No      0.160298        0.038774
     Yes     0.163863        0.039389

In [ ]:
#you can specify a list of functions to apply to all of the columns or different functions per column
#all columns
functions = ['count', 'mean', 'max']

In [ ]:
grouped['tip_pct', 'total_bill'].agg(functions)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

            tip_pct                     total_bill
              count      mean       max      count       mean    max
day  smoker
Fri  No           4  0.151650  0.187735          4  18.420000  22.75
     Yes         15  0.174783  0.263480         15  16.813333  40.17
Sat  No          45  0.158048  0.291990         45  19.661778  48.33
     Yes         42  0.147906  0.325733         42  21.276667  50.81
Sun  No          57  0.160113  0.252672         57  20.506667  48.17
     Yes         19  0.187250  0.710345         19  24.120000  45.35
Thur No          45  0.160298  0.266312         45  17.113111  41.19
     Yes         17  0.163863  0.241255         17  19.190588  43.11

In [ ]:
#aggregation on a selection of the columns

In [ ]:
grouped.agg({'tip' : np.max, 'size' : 'sum'})

               tip  size
day  smoker
Fri  No       3.50     9
     Yes      4.73    31
Sat  No       9.00   115
     Yes     10.00   104
Sun  No       6.00   167
     Yes      6.50    49
Thur No       6.70   112
     Yes      5.00    40

## [BONUS] Apply: General split-apply-combine

- We want to select the top five values by group

In [ ]:
def top(df, n=5, column='tip_pct'):
    return df.sort_values(by=column)[-n:]

In [ ]:
top(tips, n=6)

     total_bill   tip smoker  day    time  size   tip_pct
109       14.31  4.00    Yes  Sat  Dinner     2  0.279525
183       23.17  6.50    Yes  Sun  Dinner     4  0.280535
232       11.61  3.39     No  Sat  Dinner     2  0.291990
67         3.07  1.00    Yes  Sat  Dinner     1  0.325733
178        9.60  4.00    Yes  Sun  Dinner     2  0.416667
172        7.25  5.15    Yes  Sun  Dinner     2  0.710345

In [ ]:
tips[["day","total_bill"]].groupby(["day"]).max()

      total_bill
day
Fri        40.17
Sat        50.81
Sun        48.17
Thur       43.11

In [ ]:
tips[["day","total_bill"]].groupby("day").apply(top, column="total_bill")

           day  total_bill
day
Fri  91    Fri       22.49
     94    Fri       22.75
     96    Fri       27.28
     90    Fri       28.97
     95    Fri       40.17
Sat  23    Sat       39.42
     102   Sat       44.30
     59    Sat       48.27
     212   Sat       48.33
     170   Sat       50.81
Sun  11    Sun       35.26
     112   Sun       38.07
     184   Sun       40.55
     182   Sun       45.35
     156   Sun       48.17
Thur 83   Thur       32.68
     141  Thur       34.30
     85   Thur       34.83
     142  Thur       41.19
     197  Thur       43.11

In [ ]:
tips[["day","total_bill"]].groupby("day").apply(top, n=1, column="total_bill")

           day  total_bill
day
Fri  95    Fri       40.17
Sat  170   Sat       50.81
Sun  156   Sun       48.17
Thur 197  Thur       43.11

## Pivot Tables 

- A pivot table 
    - aggregates a table of data by one or more keys, 
    - arranges the data in a rectangle with some of the group keys along the rows and the columns.

In [ ]:
tips.head(10)

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808
5       25.29  4.71     No  Sun  Dinner     4  0.186240
6        8.77  2.00     No  Sun  Dinner     2  0.228050
7       26.88  3.12     No  Sun  Dinner     4  0.116071
8       15.04  1.96     No  Sun  Dinner     2  0.130319
9       14.78  3.23     No  Sun  Dinner     2  0.218539

In [ ]:
tips.pivot_table(index=['day', 'smoker']) # the default aggregation type is mean

                 size       tip   tip_pct  total_bill
day  smoker
Fri  No      2.250000  2.812500  0.151650   18.420000
     Yes     2.066667  2.714000  0.174783   16.813333
Sat  No      2.555556  3.102889  0.158048   19.661778
     Yes     2.476190  2.875476  0.147906   21.276667
Sun  No      2.929825  3.167895  0.160113   20.506667
     Yes     2.578947  3.516842  0.187250   24.120000
Thur No      2.488889  2.673778  0.160298   17.113111
     Yes     2.352941  3.030000  0.163863   19.190588

In [ ]:
tips.pivot_table(index=['day', 'smoker'], aggfunc='sum')

             size     tip   tip_pct  total_bill
day  smoker
Fri  No         9   11.25  0.606602       73.68
     Yes       31   40.71  2.621746      252.20
Sat  No       115  139.63  7.112145      884.78
     Yes      104  120.77  6.212055      893.62
Sun  No       167  180.57  9.126438     1168.88
     Yes       49   66.82  3.557756      458.28
Thur No       112  120.32  7.213414      770.09
     Yes       40   51.51  2.785676      326.24

In [ ]:
tips.pivot_table(index=['day', 'size'], columns='smoker')

                tip             tip_pct           total_bill
smoker           No       Yes        No       Yes         No        Yes
day  size
Fri  1          NaN  1.920000       NaN  0.223776        NaN   8.580000
     2     2.750000  2.620000  0.139622  0.175402  19.233333  15.650000
     3     3.000000       NaN  0.187735       NaN  15.980000        NaN
     4          NaN  4.730000       NaN  0.117750        NaN  40.170000
Sat  1     1.000000  1.000000  0.137931  0.325733   7.250000   3.070000
     2     2.563200  2.476786  0.162705  0.148668  16.026400  17.561071
     3     3.412500  4.568333  0.154661  0.144995  21.962500  32.603333
     4     4.800000  3.335000  0.150096  0.124515  30.474286  29.178333
     5          NaN  3.000000       NaN  0.106572        NaN  28.150000
Sun  2     2.582222  3.345000  0.168859  0.207893  15.642222  21.875000
     3     2.937273  3.625000  0.152663  0.152660  20.478182  26.875000
     4     3.962500  5.090000  0.148143  0.193370  26.410625  28.910000
     5     5.070000  2.000000  0.206928  0.065660  25.270000  30.460000
     6     5.000000       NaN  0.103799       NaN  48.170000        NaN
Thur 1     1.830000       NaN  0.181728       NaN  10.070000        NaN
     2     2.341714  2.713846  0.165827  0.158843  14.288857  17.493846
     3     1.770000  3.615000  0.084246  0.204952  20.730000  17.590000
     4     4.030000  4.500000  0.138919  0.155410  28.703333  31.820000
     5     5.000000       NaN  0.121389       NaN  41.190000        NaN
     6     5.300000       NaN  0.173706       NaN  30.383333        NaN

In [ ]:
tips.pivot_table(index=['day', 'size'], columns='smoker', margins=True)

                tip                      ... total_bill
smoker           No       Yes       All  ...         No        Yes        All
day  size                                ...
Fri  1          NaN  1.920000  1.920000  ...        NaN   8.580000   8.580000
     2     2.750000  2.620000  2.644375  ...  19.233333  15.650000  16.321875
     3     3.000000       NaN  3.000000  ...  15.980000        NaN  15.980000
     4          NaN  4.730000  4.730000  ...        NaN  40.170000  40.170000
Sat  1     1.000000  1.000000  1.000000  ...   7.250000   3.070000   5.160000
     2     2.563200  2.476786  2.517547  ...  16.026400  17.561071  16.837170
     3     3.412500  4.568333  3.797778  ...  21.962500  32.603333  25.509444
     4     4.800000  3.335000  4.123846  ...  30.474286  29.178333  29.876154
     5          NaN  3.000000  3.000000  ...        NaN  28.150000  28.150000
Sun  2     2.582222  3.345000  2.816923  ...  15.642222  21.875000  17.560000
     3     2.937273  3.625000  3.120667  ...  20.478182  26.875000  22.184000
     4     3.962500  5.090000  4.087778  ...  26.410625  28.910000  26.688333
     5     5.070000  2.000000  4.046667  ...  25.270000  30.460000  27.000000
     6     5.000000       NaN  5.000000  ...  48.170000        NaN  48.170000
Thur 1     1.830000       NaN  1.830000  ...  10.070000        NaN  10.070000
     2     2.341714  2.713846  2.442500  ...  14.288857  17.493846  15.156875
     3     1.770000  3.615000  2.692500  ...  20.730000  17.590000  19.160000
     4     4.030000  4.500000  4.218000  ...  28.703333  31.820000  29.950000
     5     5.000000       NaN  5.000000  ...  41.190000        NaN  41.190000
     6     5.300000       NaN  5.300000  ...  30.383333        NaN  30.383333
All        2.991854  3.008710  2.998279  ...  19.188278  20.756344  19.785943

[21 rows x 9 columns]

In [ ]:
tips.pivot_table(index=['day', 'size'], columns='smoker', margins=True, fill_value=-1000)

                   tip               ...   total_bill
smoker              No          Yes  ...          Yes        All
day  size                            ...
Fri  1    -1000.000000     1.920000  ...     8.580000   8.580000
     2        2.750000     2.620000  ...    15.650000  16.321875
     3        3.000000 -1000.000000  ... -1000.000000  15.980000
     4    -1000.000000     4.730000  ...    40.170000  40.170000
Sat  1        1.000000     1.000000  ...     3.070000   5.160000
     2        2.563200     2.476786  ...    17.561071  16.837170
     3        3.412500     4.568333  ...    32.603333  25.509444
     4        4.800000     3.335000  ...    29.178333  29.876154
     5    -1000.000000     3.000000  ...    28.150000  28.150000
Sun  2        2.582222     3.345000  ...    21.875000  17.560000
     3        2.937273     3.625000  ...    26.875000  22.184000
     4        3.962500     5.090000  ...    28.910000  26.688333
     5        5.070000     2.000000  ...    30.460000  27.000000
     6        5.000000 -1000.000000  ... -1000.000000  48.170000
Thur 1        1.830000 -1000.000000  ... -1000.000000  10.070000
     2        2.341714     2.713846  ...    17.493846  15.156875
     3        1.770000     3.615000  ...    17.590000  19.160000
     4        4.030000     4.500000  ...    31.820000  29.950000
     5        5.000000 -1000.000000  ... -1000.000000  41.190000
     6        5.300000 -1000.000000  ... -1000.000000  30.383333
All           2.991854     3.008710  ...    20.756344  19.785943

[21 rows x 9 columns]

## [Bonus] Cross-Tabulations: Crosstab
- A cross-tabulation (or crosstab for short) is a special case of a pivot table that computes group frequencies.

In [ ]:
states= ['USA','USA','UK','IT','UK','UK','IT','USA']
gender= ['M','F','F','M','M','M','F','M']

In [ ]:
data = pd.DataFrame({'states':states,'gender':gender})

In [ ]:
data

  states gender
0    USA      M
1    USA      F
2     UK      F
3     IT      M
4     UK      M
5     UK      M
6     IT      F
7    USA      M

In [ ]:
pd.crosstab(data.states, data.gender)

gender  F  M
states
IT      1  1
UK      1  2
USA     1  2

In [ ]:
pd.crosstab(data.gender, data.states)

states  IT  UK  USA
gender
F        1   1    1
M        1   2    2

In [ ]:
pd.crosstab(data.gender, data.states, margins=True)

states  IT  UK  USA  All
gender
F        1   1    1    3
M        1   2    2    5
All      2   3    3    8