# Preprocessing data

### Standardization, or mean removal and variance scaling

Standardization of datasets is a common requirement for many machine learning estimators implemented in scikit-learn; 

In practice we often ignore the shape of the distribution and just transform the data to center it by removing the mean value of each feature, then scale it by dividing non-constant features by their standard deviation.

In [1]:
from sklearn import preprocessing
import numpy as np
import pandas as pd

X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

X_scaled = preprocessing.scale(X_train)

X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [2]:
X_train.std(axis=0)

array([0.81649658, 0.81649658, 1.24721913])

In [3]:
X_train.mean(axis=0)

array([1.        , 0.        , 0.33333333])

In [4]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [5]:
X_scaled.std(axis=0)

array([1., 1., 1.])

The standard score of a sample x is calculated as:
<tt>z = (x - u) / s</tt>
where u is the mean of the training samples or zero if <tt>with_mean=False</tt>, and s is the standard deviation of the training samples or one if <tt>with_std=False</tt>.


The preprocessing module further provides a utility class StandardScaler that implements the Transformer API to compute the mean and standard deviation on a training set so as to be able to later reapply the same transformation on the testing set.

In [6]:
sss = preprocessing.StandardScaler()
scaler = sss.fit(X_train)

In [7]:
scaler

StandardScaler()

In [8]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [9]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [10]:
scaler.transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [11]:
scaler.fit(X_train)
scaler.transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [12]:
scaler.fit_transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

The scaler instance can then be used on new data to transform it the same way it did on the training set

In [ ]:
X_test = [[-1., 1., 0.]]
scaler.transform(X_test)

array([[-2.44948974,  1.22474487, -0.26726124]])

### Scaling features to a range

An alternative standardization is scaling features to lie between a given minimum and maximum value, often between zero and one, or so that the maximum absolute value of each feature is scaled to unit size.

In [13]:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [14]:
min_max_scaler = preprocessing.MinMaxScaler() # default [0,1]

In [15]:
min_max_scaler.fit(X_train)

MinMaxScaler()

In [16]:
 min_max_scaler.transform(X_train)

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [17]:
X_train_minmax = min_max_scaler.fit_transform(X_train)

In [18]:
X_train_minmax

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [ ]:
X_test = np.array([[-3., -1.,  4.]])
X_test_minmax = min_max_scaler.transform(X_test)
X_test_minmax

array([[-1.5       ,  0.        ,  1.66666667]])

The transformation is computed as:

<tt>X_scaled = scale * X + min - X.min(axis=0) * scale</tt>

where <tt>scale = (max - min) / (X.max(axis=0) - X.min(axis=0))</tt>

In [ ]:
min_max_scaler.scale_

If your data contains many outliers, scaling using the mean and variance of the data is likely to not work very well. In these cases, you can use robust_scale and RobustScaler as drop-in replacements instead. They use more robust estimates for the center and range of your data.

In [ ]:
from sklearn.preprocessing import RobustScaler
X = [[ 1., -2.,  2.],
     [ -2.,  1.,  3.],
     [ 4.,  1., -2.]]
X

[[1.0, -2.0, 2.0], [-2.0, 1.0, 3.0], [4.0, 1.0, -2.0]]

In [ ]:
transformer = RobustScaler().fit(X)

In [ ]:
transformer

RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
             with_scaling=True)

In [ ]:
transformer.scale_

array([3. , 1.5, 2.5])

In [ ]:
transformer.transform(X)

array([[ 0. , -2. ,  0. ],
       [-1. ,  0. ,  0.4],
       [ 1. ,  0. , -1.6]])

## Normalization

Normalization is the process of scaling individual samples to have unit norm. This process can be useful if you plan to use a quadratic form such as the dot-product or any other kernel to quantify the similarity of any pair of samples.

In [19]:
X = np.array([[1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]])
X_normalized = preprocessing.normalize(X, norm='l2')

In [20]:
np.sqrt(1**2 * 2**2)

2.0

In [21]:
1 / 2.0

0.5

In [22]:
X_normalized

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

##  Encoding categorical features

In [ ]:
X = [['male', 'from US', 'uses Safari'], 
     ['female', 'from Europe', 'uses Firefox']]
X

[['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]

In [ ]:
enc = preprocessing.OneHotEncoder(handle_unknown='error', sparse=True)
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=True)

In [ ]:
enc.transform([['female', 'from US', 'uses Safari'],
               ['male', 'from Europe', 'uses Firefox']]).toarray()

array([[1., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 0.]])

In [ ]:
enc.transform([['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]).toarray()

array([[0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.]])

In [ ]:
enc.categories_

[array(['female', 'male'], dtype=object),
 array(['from Europe', 'from US'], dtype=object),
 array(['uses Firefox', 'uses Safari'], dtype=object)]

In [ ]:
new_features = []
for i in enc.categories_:
  for j in i:
    print(j)
    new_features.append(j)

print(new_features)

female
male
from Europe
from US
uses Firefox
uses Safari
['female', 'male', 'from Europe', 'from US', 'uses Firefox', 'uses Safari']

In [ ]:
pd.DataFrame(X, columns=['gender', 'locations', 'browser'])

   gender    locations       browser
0    male      from US   uses Safari
1  female  from Europe  uses Firefox

In [ ]:
X = [['male', 'from Asia', 'uses Safari'], ['female', 'from Europe', 'uses Firefox'], ['male', 'from Asia', 'uses Safari']]
enc.fit(X)

new_features = []
for i in enc.categories_:
  for j in i:
    new_features.append(j)


Xnew = enc.transform(X).toarray()
pd.DataFrame(Xnew, columns=new_features)

   female  male  from Asia  from Europe  uses Firefox  uses Safari
0     0.0   1.0        1.0          0.0           0.0          1.0
1     1.0   0.0        0.0          1.0           1.0          0.0
2     0.0   1.0        1.0          0.0           0.0          1.0

In [ ]:
enc.categories_

with fixed categories value

In [ ]:
genders = ['female', 'male']
locations = ['from Africa', 'from Asia', 'from Europe', 'from US']
browsers = ['uses Chrome', 'uses Firefox', 'uses IE', 'uses Safari']
enc = preprocessing.OneHotEncoder(categories=[genders, locations, browsers])

# Note that for there are missing categorical values for the 2nd and 3rd
# feature


X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X)

OneHotEncoder(categories=[['female', 'male'],
                          ['from Africa', 'from Asia', 'from Europe',
                           'from US'],
                          ['uses Chrome', 'uses Firefox', 'uses IE',
                           'uses Safari']],
              drop=None, dtype=<class 'numpy.float64'>, handle_unknown='error',
              sparse=True)

In [ ]:
enc.transform([['female', 'from Asia', 'uses Chrome']]).toarray()

array([[1., 0., 0., 1., 0., 0., 1., 0., 0., 0.]])

with unknown values

In [ ]:
enc = preprocessing.OneHotEncoder(handle_unknown='ignore', sparse=True)
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=True)

In [ ]:
enc.transform([['female', 'from Asia', 'uses Chrome']]).toarray()

array([[1., 0., 0., 0., 0., 0.]])

drop first

In [ ]:
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox'], ['male', 'from Asia', 'uses Safari'], ['male', 'from Indo', 'uses Safari']]
drop_enc = preprocessing.OneHotEncoder(drop='first').fit(X)

In [ ]:
drop_enc.categories_

[array(['female', 'male'], dtype=object),
 array(['from Asia', 'from Europe', 'from Indo', 'from US'], dtype=object),
 array(['uses Firefox', 'uses Safari'], dtype=object)]

In [ ]:
drop_enc.transform(X).toarray()

array([[1., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1.]])

In [ ]:
X

## Discretization

Discretization (otherwise known as quantization or binning) provides a way to partition continuous features into discrete values. Certain datasets with continuous features may benefit from discretization, because discretization can transform the dataset of continuous attributes to one with only nominal attributes.

In [ ]:
X = np.array([[ -3., 5., 15 ],
              [  0., 6., 14 ],
              [  6., 3., 11 ]])
est = preprocessing.KBinsDiscretizer(n_bins=[3, 2, 3], encode='ordinal').fit(X)
est

KBinsDiscretizer(encode='ordinal', n_bins=[3, 2, 3], strategy='quantile')

In [ ]:
est.transform(X)

array([[0., 1., 2.],
       [1., 1., 1.],
       [2., 0., 0.]])

Feature binarization is the process of thresholding numerical features to get boolean values. This can be useful for downstream probabilistic estimators that make assumption that the input data is distributed according to a multi-variate Bernoulli distribution.

In [ ]:
X = [[ 1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]

binarizer = preprocessing.Binarizer().fit(X)  # fit does nothing
binarizer

Binarizer(copy=True, threshold=0.0)

In [ ]:
binarizer.transform(X)

array([[1., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
binarizer = preprocessing.Binarizer(threshold=1.1)

In [ ]:
binarizer.transform(X)

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 0.]])

## Custom transformers

Often, you will want to convert an existing Python function into a transformer to assist in data cleaning or processing.

In [ ]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

transformer = FunctionTransformer(np.log1p, validate=True)
X = np.array([[0, 1], [2, 3]])
transformer.transform(X)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [ ]:
df = pd.DataFrame(X)

In [ ]:
df

   0  1
0  0  1
1  2  3

In [ ]:
transformer.transform(df)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [ ]:
transformer = FunctionTransformer(np.log1p, validate=True)

In [ ]:
transformer.transform(df)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])